#!/bin/bash

tagPushed=$(git ls-remote --tags origin | grep -c "$npm_package_version")

if [ "$tagPushed" -eq "0" ]; then echo "Current version tag doesn't exist on remote." && exit 1; fi

headerLines=$(grep -n "##" CHANGELOG.md | cut -f1 -d:)
lineNos=()
while IFS='' read -r line; do lineNos+=("$line"); done < <(echo "$headerLines")

releaseNotes=$(sed -n -e "${lineNos[0]}",$((lineNos[1]-1))p CHANGELOG.md)

# add GITHUB_HOST in case `hub` is configured to interact with github enterprise
GITHUB_HOST=github.com hub release create -m "${releaseNotes//\#\#/}" "v$npm_package_version"
